version: '3.3'

services:
  
  web:
    restart: always
    build: ./web
    image: mydjango
    env_file: ./web/.env
    volumes:
      - ./web:/code
      - /var/www/static
    ports:
      - "8000:8000"
    links:
      - db
      - setup
    #command: python manage.py runserver 0.0.0.0:8000
    #command: ls -la
    command: /usr/local/bin/gunicorn Deepqueue.wsgi:application -w 2 -b :8000
  
  db:
    restart: always
    image: postgres

  setup:
    image: mydjango
    command: ["./setup.sh"]
    volumes:
      - ./web:/code
    links:
      - db

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /var/www/static
    links:
      - web:web
