version: '3.3'

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: static_volume
        target: /var/www/static
    links:
      - web:web

  web:
    restart: always
    build: ./web
    image: mydjango
    #env_file: ./web/.env
    volumes:
      - type: volume
        source: static_volume
        target: /var/www/static
    expose:
      - "8000"
    links:
      - db
    # To change the setting from `DeepQueue.settings.docker` to `DeepQueue.settings.dev`
    #environment:
    #  - DJANGO_SETTINGS_MODULE="DeepQueue.settings.dev"
    #command: python manage.py runserver 0.0.0.0:8000
    #command: ls -la
    # command: /usr/local/bin/gunicorn DeepQueue.wsgi:application -w 2 -b :8000
    command: [sh, -c, "./setup.sh && /usr/local/bin/gunicorn DeepQueue.wsgi:application -w 2 -b :8000"]

  db:
    restart: always
    image: postgres
    expose:
      - "5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data/

  # setup:
  #   image: mydjango
  #   command: ["./setup.sh"]
  #   depends_on:
  #     - web

#  redis:
#    restart: always
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redisdata:/data

# volumes:
#   static_volume: {}

volumes:
  static_volume:
